### ISSUE TITLE
PROBLEMS AND QUESTIONS

### ISSUE THREAD

**Issue by lucasdobr15** [ws-choi/Conditioned-Source-Separation-LaSAFT#22]
Hi all right, sorry to bother you boss,

I would like to know how do I train a model using my own dataset? i already trained my own models using vocal-remover from tsurumeso, now i would like to train a new model using the wonderful Lasaft

the architecture of the vocal remove datasets looks like this:

path/to/dataset/
  +- instruments/
  | +- 01_foo_inst.wav
  | +- 02_bar_inst.mp3
  | +- ...
  +- mixtures/
       +- 01_foo_mix.wav
       +- 02_bar_mix.mp3
       +- ...

**1**. I wonder if Lasaft also allows you to train a model using only Mixture and Instrumental?

**2**. I would like to congratulate you because you are on the top 1st Music Demixing (MDX), you are a genius, you deserve the award and much more!

**3**. Also, during these past months, have you trained any other .ckpt model for Lasaft? If so, could you share with those who appreciate your work so much?

**4**. Relating a problem... why when I use the Lasaft it makes the accompaniment/stems crash during the song? this problem occurs both in the 2stems version as well as the 4stems version

Sorry for the many questions, but this is the only place I can get in touch with you, your work is beautiful,

I look forward to hearing from you,

Yours truly,
Lucas Rodrigues.

**Comment by ws-choi** [comment]
Hi, @lucasdobr15  again!
It seems that you want to build a vocal remover.
If it is not, then please let me know.

1. LaSAFT+GPoCM was initially designed for conditioned source separation, where we want to separate multiple sources with a single instance. You can train our model for vocal remover with your own dataset, though. All you need is customizing data provider for your model: https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT/tree/main/lasaft/data. Or, you might prefer to use our previous model: https://github.com/ws-choi/ISMIR2020_U_Nets_SVS. Although it was initially proposed for singing voice separation, we found that it works for other sources such as drums. I think it would also work for the vocal-removing task.

2. Thank you very much for your interest!

3. We've developed models for another MIR problem called Audio Manipulation on Specified Sources (AMSS) for several months, instead of source separation: https://github.com/kuielab/AMSS-Net. 
So we have not spent much time re-training LaSAFT+GPoCM models. You can download three different ckpts for large models from http://intelligence.korea.ac.kr/assets/ . You can download them via ```PreTrainedLaSAFTNet(model_name='lasaft_large_2020')```. If you encounter related problems, then please let me know. Also, we trained a lightweight version of our model called LightSAFT for the DMX challenge. Check the following link for details: https://github.com/ws-choi/music-demixing-challenge-starter-kit/blob/master/test_lightsaft.py

4. What does  ```crash``  mean? Are processes killed by OS? Or did the separated results contain some wired noises? Or did you perceive a kind of glitches where contexts shift unnaturally?  

Best,
Woosung Choi.

**Comment by lucasdobr15** [comment]
Hello, sorry for the delay (text translated from gtranslate)

Thank you very much for the rich information you gave me, you are amazing!

About the "crash" that I am trying to explain is like some crashes that occur in music when I listen, I will give you an example;

Go to the LaSAFT ([**DEMO PAGE**](https://lasaft.github.io/)) page,

And listen:

**1**. vanishingcheck-other (**OTHER**)
**4**. feelthisbreeze-other (**OTHER**)
         **and more**... 

Did you notice that when listening to the music (OTHERS) there are some parts that give a "block"?

**(1)** I would like to know the reason for giving these crashes and, if it is possible to somehow fix it?

Another thing, I really wanted you to dedicate yourself more to LaSAFT, I don’t know if you know the artificial intelligence you created, it’s unique, it surpasses even that of the [tsurumeso](**url**) that until then was the best

**(2)** Take time to simplify LaSAFT (showing step by step how to train a model (with my own dataset),

LaSAFT is very promising and has everything to be the best source of music separation in the world

By the way, I created a collaboration for **[LaSAFT 2021](https://colab.research.google.com/drive/1ENYtEjEunxFstfZf5S_hAhg8-P4zN7Hk?usp=sharing)** and for **[LightSAFT](https://colab.research.google.com/drive/1mbZ-24mq9_N-pcz17Ab7TBXsznG6-uUB?usp=sharing)**, (sorry, but I suck at codes, I just play games), but it's there for those who want to use it

Regards,
Lucas Rodrigues
